on: push

jobs: 
    build-node:
        runs-on: ubuntu-latest
        container: node:21
        steps:
            - run: node --version
            - run: npm --version
            - run: node server.js